version: '3.7'

services:
  node:
    image: "node:11"
    working_dir: /code
    command: bash -c "node main.js"
    restart: always
    environment:
      ROOT_URL: ${ROOT_URL}
      MONGO_URL: mongodb://db:27017/app
      PORT: 80
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./build:/code
  db:
    image: mongo
    restart: always
